// User
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const CLEAR_ERROR = 'CLEAR_ERROR';

// TodoList
export const GET_TODO_LIST_REQUEST = 'GET_TODO_LIST_REQUEST';
export const GET_TODO_LIST_SUCCESS = 'GET_TODO_LIST_SUCCESS';
export const GET_TODO_LIST_FAIL = 'GET_TODO_LIST_FAIL';
export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO_STATE = 'TOGGLE_TODO_STATE';
export const DELETE_TODO = 'DELETE_TODO';
export const SET_TODO_LIST_FILTER = 'SET_TODO_LIST_FILTER';
